spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Zheng-Hai-Long/config-repo.git
          username: 13260541671@163.com
          password: zhl77520.
          basedir: E:\GitRep\config\basedir
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8864
